farmacia/account/urls.py
from django.urls import path
from . import views

app_name='account'
urlpatterns = [
    # Ruta para cerrar la sesión del usuario
    path("logout/", views.logout_view, name="logout"),
    
    # Ruta correspondiente al perfil del usuario
    path("profile/", views.profile, name="profile"),
    
    # Ruta para crear un nuevo usuario
    path("user_register/", views.user_register, name="user_register"),
    
    # Ruta para editar los datos de un usuario registrado
    path("edit_user_profile/", views.edit_user_profile, name="edit_user_profile"),
]

farmacia/farmacia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),
    
    # Autenticación de usuarios
    path('accounts/', include('django.contrib.auth.urls')),
    
    # Autenticación de usuarios
    path('accounts/', include('account.urls')),
    
    # Página Principal Farmacia
    path('webfarmacia/', include('webfarmacia.urls')),
    
    # Cliente
    path('cliente/', include('cliente.urls')),
    
    # Empleado
    path('empleado/', include('empleado.urls')),
    
    # Proveedor
    path('proveedor/', include('proveedor.urls')),
    
    # Producto
    path('producto/', include('producto.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

farmacia/producto/urls.py
from django.urls import path
from . import views

app_name='producto'
urlpatterns = [    
    # Ruta que permite obtener y visualizar el listado de clientes registrados
    path('ListarProductos/', views.ListarProductos, name='listarproductos'),
        
    # Ruta que permite agregar un nuevo cliente
    path('AgregarProducto/', views.AgregarProducto, name='agregarproducto'),
    
    # Ruta que permite obtener el detalle del cliente seleccionado
    path('DetalleProducto/<int:id>', views.DetalleProducto, name='detalleproducto'),
    
    # Ruta que permite actualizar la información de un cliente seleccionado
    path('ActualizarProducto/<int:id>', views.ActualizarProducto, name='actualizarproducto'),
    
    # Ruta que permite eliminar la información de un cliente seleccionado
    path('EliminarProducto/<int:id>', views.EliminarProducto, name='eliminarproducto'),
]

farmacia/webfarmacia/urls.py
from django.urls import path
from . import views

app_name='webfarmacia'
urlpatterns = [
    # Ruta principal de la aplicación creada en Django
    path('', views.index, name='indexFarmacia'),
]

farmacia/producto/models.py
from django.db import models
from proveedor.models import Proveedor
from django.db.models.deletion import PROTECT

# Create your models here.
class Categoria(models.Model):
    nombre = models.CharField(max_length=100, null=False)
    
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    nombre = models.CharField(max_length=100, null=False)
    cantidad_disponible = models.IntegerField(null=False)
    fecha_compra = models.DateTimeField(auto_now_add=True)
    fecha_vencimiento = models.DateTimeField()
    categoria = models.ForeignKey(Categoria, on_delete=models.PROTECT)
    proveedor = models.ForeignKey(Proveedor, on_delete=models.PROTECT)
    descripcion = models.TextField(max_length=500)
    imagen = models.ImageField(upload_to='imagen_producto', null=True)

farmacia/producto/forms.py
from django.forms import ModelForm, widgets
from django import forms
from django.core.validators import EmailValidator
from proveedor.models import Proveedor
from .models import Categoria, Producto
from bootstrap_datepicker_plus import DatePickerInput
from django.core.files.images import get_image_dimensions

class AgregarProductoForm(forms.Form):
    nombre = forms.CharField(label='Nombre', min_length=3, max_length=14)
    cantidad_disponible = forms.IntegerField(label='Stock')
    fecha_vencimiento = forms.DateField(label='Fecha de Vencimiento', widget=DatePickerInput(format='%Y-%m-%d'))
    categoria = forms.ModelChoiceField(label='Categoría', queryset=Categoria.objects.all())
    proveedor = forms.ModelChoiceField(label='Proveedor', queryset=Proveedor.objects.all())
    descripcion = forms.CharField(label='Descripción', widget=forms.Textarea(attrs={'rows': 1, 'cols': 85}), max_length=500)
    imagen = forms.ImageField(widget=forms.FileInput,)
    
    """ Este método permite establecer las dimensiones permitidas para la imagen """
    def clean_imagen(self):
        imagen = self.cleaned_data['imagen']
        
        # Obtención de las dimensiones de la imegen
        widht, height = get_image_dimensions(imagen)
        
        # Establecimiento de las dimenciones permitidas
        max_widht = max_height = 600
        
        # Validación de las dimesiones de la imagen
        if widht > max_widht or height > max_height:
            raise forms.ValidationError("El tamaño de la imagen no es válido. Recuerde que las dimensiones permitidas son %spx (alto) y %spx (ancho)"% (max_widht, max_height))
        
        # Validación de la extensión permitida
        img, ext = imagen.content_type.split('/')
        if not(img == 'image' and ext in ['jpeg', 'jpg', 'gif', 'png']):
            raise forms.ValidationError("Imagen no soportada, solamente soportamos: 'jpeg', 'jpg', 'gif', 'png'")
        
        # Validación del tamaño permitido
        if len(imagen) > (30 * 1024):
            raise forms.ValidationError("La imagen seleccionada supera el tamaño permitido. Por favor modifique el tamaño e intente nuevamente.")
        
        # Tamano de la imagen 1 KB equivale a 1024B
        if len(imagen) > (30 * 1024):
            raise forms.ValidationError("Imagen no puede superar los 30kb")
        
        return imagen
    
class ActualizarProductoForm(ModelForm):
    class Meta:
        model = Producto
        fields = ('nombre', 'cantidad_disponible', 'fecha_vencimiento', 'categoria', 'proveedor', 'descripcion', 'imagen',) 
        widgets = {
            'cantidad_disponible':widgets.NumberInput,
            # 'fecha_vencimiento':DatePickerInput(format='%d-%m-%Y'),
            'fecha_vencimiento':DatePickerInput ( 
                options = { 
                    "format" :  "YYYY-MM-DD" ,  # formato de fecha y hora de momento 
                    "showClose" :  True , 
                    "showClear" :  True , 
                    "showTodayButton" :  True , 
                } 
            ), 
            'categoria':widgets.Select(),
            'proveedor':widgets.Select(),
            'imagen':widgets.FileInput,
        }

farmacia/producto/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Producto
from .forms import AgregarProductoForm, ActualizarProductoForm
from bootstrap_datepicker_plus import DatePickerInput

# Create your views here.
""" Este método permite visualizar el listado de productos """
@login_required
def ListarProductos(request):
    listaProductos = Producto.objects.order_by('id')
    
    return render(request, 'listaproducto.html', {'listaProductos':listaProductos})

""" Este método permite agregar nuevos productos """
@login_required
def AgregarProducto(request):
    if request.method=='POST':
        formProducto = AgregarProductoForm(request.POST, request.FILES)
        
        if formProducto.is_valid():
            producto = Producto()
            producto.nombre = formProducto.cleaned_data['nombre']
            producto.cantidad_disponible = formProducto.cleaned_data['cantidad_disponible']
            producto.fecha_vencimiento = formProducto.cleaned_data['fecha_vencimiento']
            producto.categoria = formProducto.cleaned_data['categoria']
            producto.proveedor = formProducto.cleaned_data['proveedor']
            producto.descripcion = formProducto.cleaned_data['descripcion']
            producto.imagen = formProducto.cleaned_data['imagen']
            producto.save()
            messages.add_message(request, messages.SUCCESS, 'Datos del producto almacenados.')
            return redirect('producto:listarproductos')
    else:
        formProducto =AgregarProductoForm()
            
    return render(request, 'agregarproducto.html', {'formProducto': formProducto})

""" Este método permite obtener el detalle de un producto seleccionado """
@login_required
def DetalleProducto(request, id):
    detalleproducto = get_object_or_404(Producto, pk=id)
    return render(request, 'detalleproducto.html', {'detalleproducto':detalleproducto})

""" Este método permite actualizar un producto seleccionado """
@login_required
def ActualizarProducto(request, id):
    detalleproducto = get_object_or_404(Producto, pk=id)
    if request.method=='POST':
        formProducto = ActualizarProductoForm(request.POST, request.FILES, instance=detalleproducto)
        
        if formProducto.is_valid():
            formProducto.save()
            messages.add_message(request, messages.SUCCESS, 'Datos del producto almacenados.')
            return redirect('producto:listarproductos')
    else:
        formProducto = ActualizarProductoForm(instance=detalleproducto)
            
    return render(request, 'actualizarproducto.html', {'formProducto':formProducto, 'detalleproducto':detalleproducto})

""" Este método permite eliminar un producto seleccionado """
@login_required
def EliminarProducto(request, id):
    producto = get_object_or_404(Producto, pk=id)
    
    if producto:
        producto.delete()
    return redirect('producto:listarproductos')

farmacia/producto/templates/actualizarproducto.html
{% extends 'partials_producto/base_producto.html' %}
{% load static %}
{% load bootstrap %}

{% block content %}      
        <div class="card">
            <div class="card-header">
                <h4><b>Datos del Producto</b></h4>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {{ formProducto|bootstrap }}
                    <div class="form-group">
                    <button type="submit" class="btn btn-success mt-3">Enviar</button>
                    </div>
                    {% csrf_token %}
                </form>
            </div>
        </div>

    <div class="container-sm mt-5">
        <a href="{% url 'producto:listarproductos' %}"><img src="{% static 'img/regreso.png' %}" width="40" height="40"></a>
    </div>
  {% endblock content %}

farmacia/producto/templates/agregarproducto.html
{% extends 'partials_producto/base_producto.html' %}
{% load static %}
{% load bootstrap4 %}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
{{ form.media }}

{% block content %}    
        <div class="card">
            <div class="card-header">
                <h4><b>Datos del Producto</b></h4>
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% bootstrap_form formProducto %}
                    <div class="form-group">
                    <button type="submit" class="btn btn-success mt-3">Enviar</button>
                    </div>
                    {% csrf_token %}
                </form>
            </div>
        </div>

    <div class="container-sm mt-5">
        <a href="{% url 'producto:listarproductos' %}"><img src="{% static 'img/regreso.png' %}" width="30" height="30"></a>
    </div>
  {% endblock content %}

farmacia/producto/templates/detalleproducto.html
{% extends 'partials_producto/base_producto.html' %}
{% load bootstrap %}
    
{% block content %}    
        <div class="card text-center">
            <div class="card-header">
                <h3><b>Información Registrada</b> </h3>
            </div>
            <div class="card-body">
                <div class="row mt-4">
                    <div class="col-md-4 offset-md-4">
                        <img id="imageUserAvatar" class="rounded img-fluid" src="{{ MEDIA_URL }}{{detalleproducto.imagen}}">
                    </div>
                </div>
                <p class="card-text"><b>Nombre: </b>{{detalleproducto.nombre}}</p>
                <p class="card-text"><b>Fecha de Compra: </b>{{detalleproducto.fecha_compra}}</p>
                <p class="card-text"><b>Fecha de Vencimiento: </b>{{detalleproducto.fecha_vencimiento}}</p>                
                <p class="card-text"><b>Categoría: </b>{{detalleproducto.categoria}}</p>
                <p class="card-text"><b>Proveedor: </b>{{detalleproducto.proveedor}}</p>
                <p class="card-text"><b>Stock Disponible: </b>{{detalleproducto.cantidad_disponible}}</p>
                <p class="card-text"><b>Descripción: </b>{{detalleproducto.descripcion}}</p>                
                <a href="{% url 'producto:listarproductos' %}" class="btn btn-outline-primary">Regresar</a>
            </div>
        </div>
{% endblock content %}

farmacia/producto/templates/listaproducto.html
{% extends 'partials_producto/base_producto.html' %}
{% load static %}

    {% if  messages %}            
        {% for message in messages %}
            <div class="alert {% if message.tags %} alert-{{message.tags}} {% endif %}">{{ message }}</div>
        {% endfor %}            
    {% endif %}

{% block content %}
        <table class="table table-striped table-hover">
            <thead>
                {% comment %} <th>ID</th> {% endcomment %}
                <th>Nombre</th>
                <th>Fecha Vencimiento</th>
                <th>Stock Disponible</th>
                <th>Categoría</th>
                <th>Proveedor</th>
                <th></th>
                <th></th>
                <th></th>
            </thead>
            <tbody>
            {% for producto in listaProductos %}
                <tr>
                    {% comment %} <th>{{cliente.id}}</th> {% endcomment %}
                    <th>{{producto.nombre}}</th>
                    <th>{{producto.fecha_vencimiento}}</th>
                    <th>{{producto.cantidad_disponible}}</th>
                    <th>{{producto.categoria}}</th>
                    <th>{{producto.proveedor}}</th>
                    <th><a href="{% url 'producto:detalleproducto' producto.id %}"><img src="{% static 'img/detalle.png' %}" width="35" height="35"></a></th>
                    <th><a href="{% url 'producto:actualizarproducto' producto.id %}"><img src="{% static 'img/editar.png' %}" width="34" height="34"></a></th>
                    <th><a href="{% url 'producto:eliminarproducto' producto.id %}"><img src="{% static 'img/eliminar.png' %}" width="34" height="34"></a></th>                    
                </tr>            
            </tbody>
            {% endfor %}
        </table>
    </div>    
    
    <div class="container-sm mt-5">
        <a href="{% url 'webfarmacia:indexFarmacia' %}"><img src="{% static 'img/regreso.png' %}" width="40" height="40"></a>
    </div>
{% endblock content %}