farmacia/account/urls.py
from django.urls import path
from . import views

app_name='account'
urlpatterns = [
    # Ruta para cerrar la sesión del usuario
    path("logout/", views.logout_view, name="logout"),
    
    # Ruta correspondiente al perfil del usuario
    path("profile/", views.profile, name="profile"),
    
    # Ruta para crear un nuevo usuario
    path("user_register/", views.user_register, name="user_register"),
    
    # Ruta para editar los datos de un usuario registrado
    path("edit_user_profile/", views.edit_user_profile, name="edit_user_profile"),
]

farmacia/cliente/urls.py
from django.urls import path
from . import views

app_name='cliente'
urlpatterns = [    
    # Ruta que permite obtener y visualizar el listado de clientes registrados
    path('lista', views.lista, name='listaCliente'),
        
    # Ruta que permite agregar un nuevo cliente
    path('agregar', views.agregar, name='agregarCliente'),
    
    # Ruta que permite obtener el detalle del cliente seleccionado
    path('detalle/<int:id>', views.detalle, name='detalleCliente'),
    
    # Ruta que permite actualizar la información de un cliente seleccionado
    path('actualizar/<int:id>', views.actualizar, name='actualizarCliente'),
    
    # Ruta que permite eliminar la información de un cliente seleccionado
    path('eliminar/<int:id>', views.eliminar, name='eliminarCliente'),
]

farmacia/empleado/urls.py
from django.urls import path
from . import views

app_name='empleado'
urlpatterns = [    
    # Ruta que permite obtener y visualizar el listado de clientes registrados
    path('ListarEmpleados/', views.ListarEmpleados, name='listarempleados'),
        
    # Ruta que permite agregar un nuevo cliente
    path('AgregarEmpleado/', views.AgregarEmpleado, name='agregarempleado'),
    
    # Ruta que permite obtener el detalle del cliente seleccionado
    path('DetalleEmpleado/<int:id>', views.DetalleEmpleado, name='detallempleado'),
    
    # Ruta que permite actualizar la información de un cliente seleccionado
    path('ActualizarEmpleado/<int:id>', views.ActualizarEmpleado, name='actualizarempleado'),
    
    # Ruta que permite eliminar la información de un cliente seleccionado
    path('EliminarEmpleado/<int:id>', views.EliminarEmpleado, name='eliminarempleado'),
]

farmacia/farmacia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),
    
    # Autenticación de usuarios
    path('accounts/', include('django.contrib.auth.urls')),
    
    # Autenticación de usuarios
    path('accounts/', include('account.urls')),
    
    # Página Principal Farmacia
    path('webfarmacia/', include('webfarmacia.urls')),
    
    # Cliente
    path('cliente/', include('cliente.urls')),
    
    # Empleado
    path('empleado/', include('empleado.urls')),
    
    # Proveedor
    path('proveedor/', include('proveedor.urls')),
    
    # Producto
    path('producto/', include('producto.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

farmacia/producto/urls.py
from django.urls import path
from . import views

app_name='producto'
urlpatterns = [    
    # Ruta que permite obtener y visualizar el listado de clientes registrados
    path('ListarProductos/', views.ListarProductos, name='listarproductos'),
        
    # Ruta que permite agregar un nuevo cliente
    path('AgregarProducto/', views.AgregarProducto, name='agregarproducto'),
    
    # Ruta que permite obtener el detalle del cliente seleccionado
    path('DetalleProducto/<int:id>', views.DetalleProducto, name='detalleproducto'),
    
    # Ruta que permite actualizar la información de un cliente seleccionado
    path('ActualizarProducto/<int:id>', views.ActualizarProducto, name='actualizarproducto'),
    
    # Ruta que permite eliminar la información de un cliente seleccionado
    path('EliminarProducto/<int:id>', views.EliminarProducto, name='eliminarproducto'),
]

farmacia/proveedor/urls.py
from django.urls import path
from . import views

app_name='proveedor'
urlpatterns = [    
    # Ruta que permite obtener y visualizar el listado de clientes registrados
    path('ListarProveedores/', views.ListarProveedores, name='listarproveedores'),
        
    # Ruta que permite agregar un nuevo cliente
    path('AgregarProveedor/', views.AgregarProveedor, name='agregarproveedor'),
    
    # Ruta que permite obtener el detalle del cliente seleccionado
    path('DetalleProveedor/<int:id>', views.DetalleProveedor, name='detalleproveedor'),
    
    # Ruta que permite actualizar la información de un cliente seleccionado
    path('ActualizarProveedor/<int:id>', views.ActualizarProveedor, name='actualizarproveedor'),
    
    # Ruta que permite eliminar la información de un cliente seleccionado
    path('EliminarProveedor/<int:id>', views.EliminarProveedor, name='eliminarproveedor'),
]

farmacia/webfarmacia/urls.py
from django.urls import path
from . import views

app_name='webfarmacia'
urlpatterns = [
    # Ruta principal de la aplicación creada en Django
    path('', views.index, name='indexFarmacia'),
]

farmacia/webfarmacia/models.py
from django.db import models

# Create your models here.

farmacia/webfarmacia/views.py
from django.shortcuts import render
from producto.models import Categoria, Producto

# Create your views here.
""" Este método permite visualizar la página principal de la farmacia """
def index(request):    
    categorias = Categoria.objects.order_by('id')
    return render(request, 'index.html', {'categorias':categorias})

""" Este método permite visualizar las categorías por producto """
# def FiltrarCategoriaProducto(request):
# def ListaCategorias(request):
#     categorias = Categoria.objects.order_by('id')
#     return render(request, 'index.html', {'categorias':categorias})

farmacia/webfarmacia/templates/partials/alert.html
{% if  messages %}            
        {% for message in messages %}
            <div class="alert {% if message.tags %} alert-{{message.tags}} {% endif %}">{{ message }}</div>
        {% endfor %}            
{% endif %}

{% if msj %}
    <div class="alert {% if tag %} alert-{{ tag }} {% else %} alert-success {% endif %}">
        {{ msj }}
    </div>
{% endif %}

farmacia/webfarmacia/templates/partials/footer.html
{% load static %}

<footer class="text-center text-white" style="background-color: #e3f2fd;">
  <!-- Grid container -->
  <div class="container p-4 mt-5">
    <!-- Section: Images -->
    <section class="">
      <div class="row">
        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div class="bg-image hover-overlay ripple shadow-1-strong rounded" data-ripple-color="light">
            <img src="{% static 'img/productos/pañales.jpg' %}" class="w-100"/>
            <a href="#!">
              <div class="mask" style="background-color: rgba(251, 251, 251, 0.2);">
              </div>
            </a>
          </div>
        </div>

        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div class="bg-image hover-overlay ripple shadow-1-strong rounded" data-ripple-color="light">
            <img src="{% static 'img/productos/aspirina.png' %}" class="w-100"/>
            <a href="#!">
              <div class="mask" style="background-color: rgba(251, 251, 251, 0.2);">
              </div>
            </a>
          </div>
        </div>

        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div class="bg-image hover-overlay ripple shadow-1-strong rounded" data-ripple-color="light">
            <img src="{% static 'img/productos/Nan.jpeg' %}" class="w-100"/>
            <a href="#!">
              <div
                class="mask"
                style="background-color: rgba(251, 251, 251, 0.2);"
              ></div>
            </a>
          </div>
        </div>

        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div class="bg-image hover-overlay ripple shadow-1-strong rounded" data-ripple-color="light">
            <img src="{% static 'img/productos/iniston.jpg' %}" class="w-100"/>
            <a href="#!">
              <div class="mask" style="background-color: rgba(251, 251, 251, 0.2);">
              </div>
            </a>
          </div>
        </div>

        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div class="bg-image hover-overlay ripple shadow-1-strong rounded" data-ripple-color="light">
            <img src="{% static 'img/productos/vapopads.jpg' %}" class="w-100"/>
            <a href="#!">
              <div class="mask" style="background-color: rgba(251, 251, 251, 0.2);">
              </div>
            </a>
          </div>
        </div>

        <div class="col-lg-2 col-md-12 mb-4 mb-md-0">
          <div class="bg-image hover-overlay ripple shadow-1-strong rounded" data-ripple-color="light">
            <img src="{% static 'img/productos/pediasure.jpg' %}" class="w-100"/>
            <a href="#!">
              <div class="mask" style="background-color: rgba(251, 251, 251, 0.2);">
              </div>
            </a>
          </div>
        </div>
      </div>
    </section>
    <!-- Section: Images -->
  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3 bg-dark text-white">
        © {% now 'M Y' %}
    <a href="">Contacto</a>
</div>
  <!-- Copyright -->
</footer>

farmacia/webfarmacia/templates/partials/header_principal.html
{% load static %}
{% load bootstrap %}

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'webfarmacia:indexFarmacia' %}">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <img src="{% static 'img/farmacia.png' %}" alt="" width="50" height="50"/>
      <strong>FreLor Farmacia</strong>
    </a>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
          <!-- Opciones del menú -->
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Productos
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'producto:listarproductos' %}">Listado de Productos</a>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Personas
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'cliente:listaCliente' %}">Listado de Clientes</a>
                <a class="dropdown-item" href="{% url 'empleado:listarempleados' %}">Listado de Empleados</a>
                <a class="dropdown-item" href="{% url 'proveedor:listarproveedores' %}">Listado de Proveedores</a>
          </li>          
      </ul>
          <a class="navbar-brand" href="{% url 'account:profile' %}">
            <abbr title="Ir al perfil">Usuario conectado: {{ user.username }}</abbr>
          </a>
          <a href="{% url 'logout' %}" class="btn btn-outline-primary btn-sm my-2 my-sm-0 float-left">Cerrar Sesión</a>
        {% else %}
          <a href="{% url 'login' %}" class="btn btn-outline-primary btn-sm my-2 my-sm-0 float-left">Iniciar Sesión</a>
        {% endif %}
    </div>
  </div>
</nav>