farmacia/account/urls.py
from django.urls import path
from . import views

app_name='account'
urlpatterns = [
    # Ruta para cerrar la sesión del usuario
    path("logout/", views.logout_view, name="logout"),
    
    # Ruta correspondiente al perfil del usuario
    path("profile/", views.profile, name="profile"),
    
    # Ruta para crear un nuevo usuario
    path("user_register/", views.user_register, name="user_register"),
    
    # Ruta para editar los datos de un usuario registrado
    path("edit_user_profile/", views.edit_user_profile, name="edit_user_profile"),
]

farmacia/farmacia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),
    
    # Autenticación de usuarios
    path('accounts/', include('django.contrib.auth.urls')),
    
    # Autenticación de usuarios
    path('accounts/', include('account.urls')),
    
    # Página Principal Farmacia
    path('webfarmacia/', include('webfarmacia.urls')),
    
    # Cliente
    path('cliente/', include('cliente.urls')),
    
    # Empleado
    path('empleado/', include('empleado.urls')),
    
    # Proveedor
    path('proveedor/', include('proveedor.urls')),
    
    # Producto
    path('producto/', include('producto.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

farmacia/proveedor/urls.py
from django.urls import path
from . import views

app_name='proveedor'
urlpatterns = [    
    # Ruta que permite obtener y visualizar el listado de clientes registrados
    path('ListarProveedores/', views.ListarProveedores, name='listarproveedores'),
        
    # Ruta que permite agregar un nuevo cliente
    path('AgregarProveedor/', views.AgregarProveedor, name='agregarproveedor'),
    
    # Ruta que permite obtener el detalle del cliente seleccionado
    path('DetalleProveedor/<int:id>', views.DetalleProveedor, name='detalleproveedor'),
    
    # Ruta que permite actualizar la información de un cliente seleccionado
    path('ActualizarProveedor/<int:id>', views.ActualizarProveedor, name='actualizarproveedor'),
    
    # Ruta que permite eliminar la información de un cliente seleccionado
    path('EliminarProveedor/<int:id>', views.EliminarProveedor, name='eliminarproveedor'),
]

farmacia/webfarmacia/urls.py
from django.urls import path
from . import views

app_name='webfarmacia'
urlpatterns = [
    # Ruta principal de la aplicación creada en Django
    path('', views.index, name='indexFarmacia'),
]

farmacia/proveedor/models.py
from django.db import models
from django.db.models.deletion import PROTECT
from cliente.models import Ciudad, TipoDocumento

# Create your models here.
class Proveedor(models.Model):    
    nombre = models.CharField(max_length=255, null=False)
    direccion = models.CharField(max_length=255, null=False)
    ciudad = models.ForeignKey(Ciudad, on_delete=models.PROTECT)
    tipo_documento = models.ForeignKey(TipoDocumento, on_delete=models.PROTECT)
    numero_documento = models.CharField(max_length=20, null=False)
    telefono =  models.CharField(max_length=14, null=False)
    email =  models.CharField(max_length=50, null=False)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.nombre

farmacia/proveedor/forms.py
from django.forms import ModelForm, widgets
from django import forms
from django.core.validators import EmailValidator
from cliente.models import Ciudad, TipoDocumento
from .models import Proveedor

class AgregarProveedorForm(forms.Form):
    nombre = forms.CharField(label='Nombre', min_length=3, max_length=14)
    direccion = forms.CharField(label='Dirección', min_length=15, max_length=100)
    ciudad = forms.ModelChoiceField(label='Ciudad', queryset=Ciudad.objects.all())
    tipo_documento = forms.ModelChoiceField(label='Tipo de Documento', queryset=TipoDocumento.objects.all())
    numero_documento = forms.CharField(label='Número de Documento', min_length=3, max_length=14)
    telefono = forms.CharField(label='Teléfono', min_length=7, max_length=10)
    email = forms.CharField(label='Correo', max_length=100, validators=[EmailValidator(message='Correo inválido', whitelist='mail, gmail, outlook, hotmail, yahoo')])
    
class ActualizarProveedorForm(ModelForm):
    class Meta:
        model = Proveedor
        fields = ('nombre', 'direccion', 'ciudad', 'telefono', 'email',) 
        widgets = {
            'direccion': widgets.TextInput(),
            'ciudad': widgets.Select(),
            'telefono':widgets.NumberInput(),
            'email':widgets.EmailInput(attrs={'type': 'email'})
        }

farmacia/proveedor/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Proveedor
from .forms import AgregarProveedorForm, ActualizarProveedorForm

# Create your views here.
""" Este método permite visualizar el listado de proveedores """
@login_required
def ListarProveedores(request):
    listaProveedores = Proveedor.objects.order_by('id')
    
    return render(request, 'listaproveedor.html', {'listaProveedores':listaProveedores})

""" Este método permite agregar nuevos proveedores """
@login_required
def AgregarProveedor(request):
    if request.method=='POST':
        formProveedor = AgregarProveedorForm(request.POST)
        
        if formProveedor.is_valid():
            proveedor = Proveedor()
            proveedor.nombre = formProveedor.cleaned_data['nombre']
            proveedor.direccion = formProveedor.cleaned_data['direccion']
            proveedor.ciudad = formProveedor.cleaned_data['ciudad']
            proveedor.tipo_documento = formProveedor.cleaned_data['tipo_documento']
            proveedor.numero_documento = formProveedor.cleaned_data['numero_documento']
            proveedor.telefono = formProveedor.cleaned_data['telefono']
            proveedor.email = formProveedor.cleaned_data['email']
            proveedor.save()
            messages.add_message(request, messages.SUCCESS, 'Datos del proveedor almacenados.')
            return redirect('proveedor:listarproveedores')
    else:
        formProveedor =AgregarProveedorForm()
            
    return render(request, 'agregarproveedor.html', {'formProveedor': formProveedor})

""" Este método permite obtener el detalle del proveedor seleccionado """
@login_required
def DetalleProveedor(request, id):
    detalleproveedor = get_object_or_404(Proveedor, pk=id)
    return render(request, 'detalleproveedor.html', {'detalleproveedor':detalleproveedor})

""" Este método permite actualizar un proveedor seleccionado """
@login_required
def ActualizarProveedor(request, id):
    detalleproveedor = get_object_or_404(Proveedor, pk=id)
    if request.method=='POST':
        formProveedor = ActualizarProveedorForm(request.POST, instance=detalleproveedor)
        
        if formProveedor.is_valid():
            formProveedor.save()
            messages.add_message(request, messages.SUCCESS, 'Datos del cliente almacenados.')
            return redirect('proveedor:listarproveedores')
    else:
        formProveedor = ActualizarProveedorForm(instance=detalleproveedor)
            
    return render(request, 'actualizarproveedor.html', {'formProveedor':formProveedor, 'detalleproveedor':detalleproveedor})

""" Este método permite eliminar un cliente seleccionado """
@login_required
def EliminarProveedor(request, id):
    proveedor = get_object_or_404(Proveedor, pk=id)
    
    if proveedor:
        proveedor.delete()
    return redirect('proveedor:listarproveedores')

farmacia/proveedor/templates/actualizarproveedor.html
{% extends 'partials_proveedor/base_proveedor.html' %}
{% load static %}
{% load bootstrap %}

{% block content %}      
        <div class="card">
            <div class="card-header">
                <h4><b>Datos del Proveedor</b></h4>
            </div>
            <div class="card-body">
                <form action="{% url 'proveedor:actualizarproveedor' detalleproveedor.id %}" method="post">
                    {{ formProveedor|bootstrap }}
                    <div class="form-group">
                    <button type="submit" class="btn btn-success mt-3">Enviar</button>
                    </div>
                    {% csrf_token %}
                </form>
            </div>
        </div>

    <div class="container-sm mt-5">
        <a href="{% url 'proveedor:listarproveedores' %}"><img src="{% static 'img/regreso.png' %}" width="40" height="40"></a>
    </div>
  {% endblock content %}

farmacia/proveedor/templates/agregarproveedor.html
{% extends 'partials_proveedor/base_proveedor.html' %}
{% load static %}
{% load bootstrap %}
    
{% block content %}
        <div class="card">
            <div class="card-header">
                <h4><b>Datos del Proveedor</b></h4>
            </div>
            <div class="card-body">
                <form action="{% url 'proveedor:agregarproveedor' %}" method="post">
                    {{ formProveedor|bootstrap }}
                    <div class="form-group">
                    <button type="submit" class="btn btn-success mt-3">Enviar</button>
                    </div>
                    {% csrf_token %}
                </form>
            </div>
        </div>

    <div class="container-sm mt-5">
        <a href="{% url 'proveedor:listarproveedores' %}"><img src="{% static 'img/regreso.png' %}" width="30" height="30"></a>
    </div>
  {% endblock content %}

farmacia/proveedor/templates/detalleproveedor.html
{% extends 'partials_proveedor/base_proveedor.html' %}
{% load bootstrap %}
    
{% block content %}    
        <div class="card text-center">
            <div class="card-header">
                <h3><b>Información Registrada</b> </h3>
            </div>
            <div class="card-body">
                <p class="card-text"><b>Nombre: </b>{{detalleproveedor.nombre}}
                <p class="card-text"><b>Dirección: </b>{{detalleproveedor.direccion}}</p>
                <p class="card-text"><b>Ciudad de residencia: </b>{{detalleproveedor.ciudad}}</p>
                <p class="card-text"><b>Tipo de documento: </b>{{detalleproveedor.tipo_documento}}</p>
                <p class="card-text"><b>Número de documento: </b>{{detalleproveedor.numero_documento}}</p>
                <p class="card-text"><b>Teléfono: </b>{{detalleproveedor.telefono}}</p>
                <p class="card-text"><b>Email: </b>{{detalleproveedor.email}}</p>
                <a href="{% url 'proveedor:listarproveedores' %}" class="btn btn-outline-primary">Regresar</a>
            </div>
        </div>
{% endblock content %}

farmacia/proveedor/templates/listaproveedor.html
{% extends 'partials_proveedor/base_proveedor.html' %}
{% load static %}

    {% if  messages %}            
        {% for message in messages %}
            <div class="alert {% if message.tags %} alert-{{message.tags}} {% endif %}">{{ message }}</div>
        {% endfor %}            
    {% endif %}

{% block content %}
        <table class="table table-striped table-hover">
            <thead>
                {% comment %} <th>ID</th> {% endcomment %}
                <th>Nombre</th>
                <th>Tipo Documento</th>
                <th>Dirección</th>
                <th>Teléfono</th>
                <th>Email</th>
                <th></th>
                <th></th>
                <th></th>
            </thead>
            <tbody>
            {% for proveedor in listaProveedores %}
                <tr>
                    {% comment %} <th>{{cliente.id}}</th> {% endcomment %}
                    <th>{{proveedor.nombre}}</th>
                    <th>{{proveedor.tipo_documento}}</th>
                    <th>{{proveedor.direccion}}</th>
                    <th>{{proveedor.telefono}}</th>
                    <th>{{proveedor.email}}</th>
                    <th><a href="{% url 'proveedor:detalleproveedor' proveedor.id %}"><img src="{% static 'img/detalle.png' %}" width="35" height="35"></a></th>
                    <th><a href="{% url 'proveedor:actualizarproveedor' proveedor.id %}"><img src="{% static 'img/editar.png' %}" width="34" height="34"></a></th>
                    <th><a href="{% url 'proveedor:eliminarproveedor' proveedor.id %}"><img src="{% static 'img/eliminar.png' %}" width="34" height="34"></a></th>
                    
                </tr>            
            </tbody>
            {% endfor %}
        </table>
    </div>    
    
    <div class="container-sm mt-5">
        <a href="{% url 'webfarmacia:indexFarmacia' %}"><img src="{% static 'img/regreso.png' %}" width="40" height="40"></a>
    </div>
{% endblock content %}