farmacia/account/urls.py
from django.urls import path
from . import views

app_name='account'
urlpatterns = [
    # Ruta para cerrar la sesión del usuario
    path("logout/", views.logout_view, name="logout"),
    
    # Ruta correspondiente al perfil del usuario
    path("profile/", views.profile, name="profile"),
    
    # Ruta para crear un nuevo usuario
    path("user_register/", views.user_register, name="user_register"),
    
    # Ruta para editar los datos de un usuario registrado
    path("edit_user_profile/", views.edit_user_profile, name="edit_user_profile"),
]

farmacia/empleado/urls.py
from django.urls import path
from . import views

app_name='empleado'
urlpatterns = [    
    # Ruta que permite obtener y visualizar el listado de clientes registrados
    path('ListarEmpleados/', views.ListarEmpleados, name='listarempleados'),
        
    # Ruta que permite agregar un nuevo cliente
    path('AgregarEmpleado/', views.AgregarEmpleado, name='agregarempleado'),
    
    # Ruta que permite obtener el detalle del cliente seleccionado
    path('DetalleEmpleado/<int:id>', views.DetalleEmpleado, name='detallempleado'),
    
    # Ruta que permite actualizar la información de un cliente seleccionado
    path('ActualizarEmpleado/<int:id>', views.ActualizarEmpleado, name='actualizarempleado'),
    
    # Ruta que permite eliminar la información de un cliente seleccionado
    path('EliminarEmpleado/<int:id>', views.EliminarEmpleado, name='eliminarempleado'),
]

farmacia/farmacia/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),
    
    # Autenticación de usuarios
    path('accounts/', include('django.contrib.auth.urls')),
    
    # Autenticación de usuarios
    path('accounts/', include('account.urls')),
    
    # Página Principal Farmacia
    path('webfarmacia/', include('webfarmacia.urls')),
    
    # Cliente
    path('cliente/', include('cliente.urls')),
    
    # Empleado
    path('empleado/', include('empleado.urls')),
    
    # Proveedor
    path('proveedor/', include('proveedor.urls')),
    
    # Producto
    path('producto/', include('producto.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)    

farmacia/webfarmacia/urls.py
from django.urls import path
from . import views

app_name='webfarmacia'
urlpatterns = [
    # Ruta principal de la aplicación creada en Django
    path('', views.index, name='indexFarmacia'),
]

farmacia/empleado/models.py
from django.db import models
from cliente.models import Sexo, Ciudad, TipoDocumento
from django.db.models.deletion import PROTECT

# Create your models here.
class Empleado(models.Model):    
    nombre = models.CharField(max_length=255, null=False)
    apellido = models.CharField(max_length=255, null=False)
    direccion = models.CharField(max_length=255, null=False)
    sexo = models.ForeignKey(Sexo, on_delete=models.PROTECT)
    ciudad = models.ForeignKey(Ciudad, on_delete=models.PROTECT)
    tipo_documento = models.ForeignKey(TipoDocumento, on_delete=models.PROTECT)
    numero_documento = models.CharField(max_length=20, null=False)
    telefono =  models.CharField(max_length=14, null=False)
    email =  models.CharField(max_length=20, null=False)
    fecha_registro = models.DateTimeField(auto_now_add=True)
    fecha_actualizacion = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.nombre + ' ' + self.apellido

farmacia/empleado/forms.py
from django.forms import ModelForm, widgets
from django import forms
from django.core.validators import EmailValidator
from cliente.models import Sexo, Ciudad, TipoDocumento
from .models import Empleado

class AgregarEmpleadoForm(forms.Form):
    nombre = forms.CharField(label='Nombre', min_length=3, max_length=14)
    apellido = forms.CharField(label='Apellido', min_length=3, max_length=14)
    direccion = forms.CharField(label='Dirección', min_length=15, max_length=100)
    sexo = forms.ModelChoiceField(label='Sexo', queryset=Sexo.objects.all())
    ciudad = forms.ModelChoiceField(label='Ciudad', queryset=Ciudad.objects.all())
    tipo_documento = forms.ModelChoiceField(label='Tipo de Documento', queryset=TipoDocumento.objects.all())
    numero_documento = forms.CharField(label='Número de Documento', min_length=3, max_length=10)
    telefono = forms.CharField(label='Teléfono', min_length=7, max_length=10)
    email = forms.CharField(label='Correo', validators=[EmailValidator(message='Correo inválido', whitelist='mail, gmail, outlook, hotmail, yahoo')])
    
class ActualizarEmpleadoForm(ModelForm):
    class Meta:
        model = Empleado
        fields = ('nombre', 'apellido', 'direccion', 'sexo', 'ciudad', 'telefono', 'email',) 
        widgets = {
            'direccion': widgets.TextInput(),
            'ciudad': widgets.Select(),
            'telefono':widgets.NumberInput(),
            'email':widgets.EmailInput(attrs={'type': 'email'})
        }

farmacia/empleado/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .models import Empleado
from .forms import ActualizarEmpleadoForm, AgregarEmpleadoForm

# Create your views here.
""" Este método permite visualizar el listado de empleados """
@login_required
def ListarEmpleados(request):
    listaEmpleados = Empleado.objects.order_by('id')
    
    return render(request, 'listaempleado.html', {'listaEmpleados':listaEmpleados})

""" Este método permite agregar nuevos empleados """
@login_required
def AgregarEmpleado(request):
    if request.method=='POST':
        formEmpleado = AgregarEmpleadoForm(request.POST)
        
        if formEmpleado.is_valid():
            empleado = Empleado()
            empleado.nombre = formEmpleado.cleaned_data['nombre']
            empleado.apellido = formEmpleado.cleaned_data['apellido']
            empleado.direccion = formEmpleado.cleaned_data['direccion']
            empleado.sexo = formEmpleado.cleaned_data['sexo']
            empleado.ciudad = formEmpleado.cleaned_data['ciudad']
            empleado.tipo_documento = formEmpleado.cleaned_data['tipo_documento']
            empleado.numero_documento = formEmpleado.cleaned_data['numero_documento']
            empleado.telefono = formEmpleado.cleaned_data['telefono']
            empleado.email = formEmpleado.cleaned_data['email']
            empleado.save()
            messages.add_message(request, messages.SUCCESS, 'Datos del empleado almacenados.')
            return redirect('empleado:listarempleados')
    else:
        formEmpleado =AgregarEmpleadoForm()
            
    return render(request, 'agregarempleado.html', {'formEmpleado': formEmpleado})

""" Este método permite obtener el detalle del empleado seleccionado """
@login_required
def DetalleEmpleado(request, id):
    detallempleado = get_object_or_404(Empleado, pk=id)
    return render(request, 'detallempleado.html', {'detallempleado':detallempleado})

""" Este método permite actualizar un empleado seleccionado """
@login_required
def ActualizarEmpleado(request, id):
    detallempleado = get_object_or_404(Empleado, pk=id)
    if request.method=='POST':
        formEmpleado = ActualizarEmpleadoForm(request.POST, instance=detallempleado)
        
        if formEmpleado.is_valid():
            formEmpleado.save()
            messages.add_message(request, messages.SUCCESS, 'Datos del cliente almacenados.')
            return redirect('empleado:listarempleados')
    else:
        formEmpleado = ActualizarEmpleadoForm(instance=detallempleado)
            
    return render(request, 'actualizarempleado.html', {'formEmpleado':formEmpleado, 'detallempleado':detallempleado})

""" Este método permite eliminar un empleado seleccionado """
@login_required
def EliminarEmpleado(request, id):
    empleado = get_object_or_404(Empleado, pk=id)
    
    if empleado:
        empleado.delete()
    return redirect('empleado:listarempleados')

farmacia/empleado/templates/actualizarempleado.html
{% extends 'partials_empleado/base_empleado.html' %}
{% load static %}
{% load bootstrap %}

{% block content %}      
        <div class="card">
            <div class="card-header">
                <h4><b>Datos del Empleado</b></h4>
            </div>
            <div class="card-body">
                <form action="{% url 'empleado:actualizarempleado' detallempleado.id %}" method="post">
                    {{ formEmpleado|bootstrap }}
                    <div class="form-group">
                    <button type="submit" class="btn btn-success mt-3">Enviar</button>
                    </div>
                    {% csrf_token %}
                </form>
            </div>
        </div>

    <div class="container-sm mt-5">
        <a href="{% url 'empleado:listarempleados' %}"><img src="{% static 'img/regreso.png' %}" width="40" height="40"></a>
    </div>
  {% endblock content %}

farmacia/empleado/templates/agregarempleado.html
{% extends 'partials_empleado/base_empleado.html' %}
{% load static %}
{% load bootstrap %}
    
{% block content %}
        <div class="card">
            <div class="card-header">
                <h4><b>Datos del Empleado</b></h4>
            </div>
            <div class="card-body">
                <form action="{% url 'empleado:agregarempleado' %}" method="post">
                    {{ formEmpleado|bootstrap }}
                    <div class="form-group">
                    <button type="submit" class="btn btn-success mt-3">Enviar</button>
                    </div>
                    {% csrf_token %}
                </form>
            </div>
        </div>

    <div class="container-sm mt-5">
        <a href="{% url 'empleado:listarempleados' %}"><img src="{% static 'img/regreso.png' %}" width="30" height="30"></a>
    </div>
  {% endblock content %}

farmacia/empleado/templates/detallempleado.html
{% extends 'partials_empleado/base_empleado.html' %}
{% load bootstrap %}
    
{% block content %}    
        <div class="card text-center">
            <div class="card-header">
                <h3><b>Información Registrada</b> </h3>
            </div>
            <div class="card-body">
                <p class="card-text"><b>Nombre: </b>{{detallempleado.nombre}} {{detallempleado.apellido}}</p>                
                <p class="card-text"><b>Dirección: </b>{{detallempleado.direccion}}</p>
                <p class="card-text"><b>Sexo: </b>{{detallempleado.sexo}}</p>
                <p class="card-text"><b>Ciudad de residencia: </b>{{detallempleado.ciudad}}</p>
                <p class="card-text"><b>Tipo de documento: </b>{{detallempleado.tipo_documento}}</p>
                <p class="card-text"><b>Número de documento: </b>{{detallempleado.numero_documento}}</p>
                <p class="card-text"><b>Teléfono: </b>{{detallempleado.telefono}}</p>
                <p class="card-text"><b>Email: </b>{{detallempleado.email}}</p>
                <a href="{% url 'empleado:listarempleados' %}" class="btn btn-outline-primary">Regresar</a>
            </div>
        </div>
{% endblock content %}

farmacia/empleado/templates/listaempleado.html
{% extends 'partials_empleado/base_empleado.html' %}
{% load static %}

    {% if  messages %}            
        {% for message in messages %}
            <div class="alert {% if message.tags %} alert-{{message.tags}} {% endif %}">{{ message }}</div>
        {% endfor %}            
    {% endif %}

{% block content %}
        <table class="table table-striped table-hover">
            <thead>
                {% comment %} <th>ID</th> {% endcomment %}
                <th>Nombre</th>
                <th>Dirección</th>
                <th>Teléfono</th>
                <th>Email</th>
                <th></th>
                <th></th>
                <th></th>
            </thead>
            <tbody>
            {% for empleado in listaEmpleados %}
                <tr>
                    {% comment %} <th>{{cliente.id}}</th> {% endcomment %}
                    <th>{{empleado.nombre}} {{empleado.apellido}}</th>
                    <th>{{empleado.direccion}}</th>
                    <th>{{empleado.telefono}}</th>
                    <th>{{empleado.email}}</th>
                    <th><a href="{% url 'empleado:detallempleado' empleado.id %}"><img src="{% static 'img/detalle.png' %}" width="35" height="35"></a></th>
                    <th><a href="{% url 'empleado:actualizarempleado' empleado.id %}"><img src="{% static 'img/editar.png' %}" width="34" height="34"></a></th>
                    <th><a href="{% url 'empleado:eliminarempleado' empleado.id %}"><img src="{% static 'img/eliminar.png' %}" width="34" height="34"></a></th>
                    
                </tr>            
            </tbody>
            {% endfor %}
        </table>
    </div>    
    
    <div class="container-sm mt-5">
        <a href="{% url 'webfarmacia:indexFarmacia' %}"><img src="{% static 'img/regreso.png' %}" width="40" height="40"></a>
    </div>
{% endblock content %}